import Head from 'next/head'

export default function Home() {
  const handleSubmit = async (event: any) => {
    event.preventDefault()
    const response = await fetch('/api/rsvp', {
      method: 'POST',
      headers: { 'Content-Type': 'application/json', },
      body: JSON.stringify({
        names: event.target.names.value,
        dietary: event.target.dietary.value,
      }),
    })
    console.log(await response.json())
  }

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <form className="mt-8 m-auto card max-w-xl bg-base-100 shadow-xl" onSubmit={handleSubmit}>
          <div className="card-body">

            <label className="my-2 input-group input-group-vertical">
              <span>Names</span>
              <input className="input input-bordered" type="text" name="names" required />
            </label>

            <label className="my-2 input-group input-group-vertical">
              <span>Dietary requirements</span>
              <input className="input input-bordered" type="text" name="dietary" required />
            </label>

            <div className="my-2 card-actions justify-end">
              <button className="btn btn-primary" type="submit">Submit</button>
            </div>
          </div>
        </form>

      </main>
    </>
  )
}
