import Head from 'next/head'

export default function Home() {
  const handleSubmit = async (event: any) => {
    event.preventDefault()
    const response = await fetch('/api/rsvp', {
      method: 'POST',
      headers: { 'Content-Type': 'application/json', },
      body: JSON.stringify({
        names: event.target.names.value,
        dietary: event.target.dietary.value,
      }),
    })
    console.log(await response.json())
  }

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <form onSubmit={handleSubmit}>
          <div>
            <label htmlFor="names">Names</label>
            <input type="text" id="names" name="names" required />
          </div>

          <div>
            <label htmlFor="dietary">Dietary requirements</label>
            <input type="text" id="dietary" name="dietary" required />
          </div>

          <button type="submit">Submit</button>
        </form>
      </main>
    </>
  )
}
